#pragma once

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <string>
#include <algorithm>
#include <nvs_flash.h>
#include <nvs.h>
#include <esp_wifi.h>
#include <esp_netif.h>
#include <esp_http_server.h>
#include <esp_ota_ops.h>
#include <esp_system.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include "StatusLedManager.h"
#include "KeyCodes.h"

extern const int DEBUG;
extern const bool LEGACY;

#define BLE_NAME_MAX_LEN 32
extern const char DEFAULT_BLE_NAME[];

// ---------------------------------------------------------------------------
// ConfigManager -- manages keymap / BLE-name NVS storage, the config AP and
// the web server routes.  All persistent settings live here.
// ---------------------------------------------------------------------------

// Config web page embedded from src/config.min.html (generated by
// scripts/minify_html.py before each build).
extern const uint8_t config_html_start[] asm("_binary_config_min_html_start");
extern const uint8_t config_html_end[]   asm("_binary_config_min_html_end");

class ConfigManager {
public:
  // Factory defaults -- mirror the original hard-coded behaviour
  static const uint8_t DEFAULT_SHORT[8];
  static const uint8_t DEFAULT_LONG[8];

  // Inject the StatusLedManager so web handlers can signal progress via LED,
  // and the firmware version string to display in the web config UI.
  void begin(StatusLedManager* led, const char* firmwareVersion);

  // Load all settings from NVS in one call.
  void loadAll();

  // ---------------------------------------------------------------------------
  // NVS -- keymaps (3 slots)
  // ---------------------------------------------------------------------------
  void saveKeymap();

  // ---------------------------------------------------------------------------
  // NVS -- active keymap index (1, 2, or 3)
  // ---------------------------------------------------------------------------
  void setActiveKeymap(int slot);

  int getActiveKeymap() const { return _activeKeymap; }

  // ---------------------------------------------------------------------------
  // NVS -- BLE device name
  // ---------------------------------------------------------------------------
  void saveBleName();

  // ---------------------------------------------------------------------------
  // NVS -- battery enable flag
  // ---------------------------------------------------------------------------
  void saveBatteryEnabled();

  void saveBLEPowerSaving();

  void saveMaxBLEConnections();

  bool    isBatteryEnabled()     const { return _batteryEnabled; }
  bool    allowBLEPowerSaving()  const { return _blePowerSaving; }
  uint8_t getMaxBLEConnections() const { return _maxBLEConnections; }

  // ---------------------------------------------------------------------------
  // NVS -- "clear bonds" flag
  // ---------------------------------------------------------------------------
  void requestClearBonds();
  bool isClearBondsRequested();
  void clearClearBondsFlag();

  // ---------------------------------------------------------------------------
  // Keymap / BLE name accessors
  // ---------------------------------------------------------------------------
  uint8_t     getShortKey(int idx) const;
  uint8_t     getLongKey(int idx)  const;
  const char* getBleName()         const { return _bleName; }

  static int btnIndex(char key);

  // ---------------------------------------------------------------------------
  // AP / HTTP server -- config mode
  // ---------------------------------------------------------------------------
  void beginConfigAP();
  void handleClient() {}
  void endConfigAP();

  bool isExitRequested() const  { return _exitConfig; }
  void setExitRequested(bool v) { _exitConfig = v; }

private:
  StatusLedManager* _led          = nullptr;
  bool              _exitConfig   = false;
  char              _firmwareVersion[32] = {};
  uint8_t           _short[3][8]  = {};
  uint8_t           _long[3][8]   = {};
  int               _activeKeymap = 1;
  bool              _batteryEnabled = false;
  bool              _blePowerSaving = false;
  uint8_t           _maxBLEConnections = 1;
  char              _bleName[BLE_NAME_MAX_LEN + 1] = "RemoteKeyboard";
  httpd_handle_t    _server    = nullptr;
  esp_netif_t*      _apNetif   = nullptr;
  const char*       _apSsid    = "RemoteKeyboard-Config";
  const char*       _apPswd    = "remotekeyboard";

  // ---------------------------------------------------------------------------
  // Individual NVS loaders (called by loadAll)
  // ---------------------------------------------------------------------------
  void _loadKeymap();
  void _loadActiveKeymap();
  void _loadBleName();
  void _loadBatteryEnabled();
  void _loadBLEPowerSaving();
  void _loadMaxBLEConnections();

  // ---------------------------------------------------------------------------
  // String helpers
  // ---------------------------------------------------------------------------
  static void        _strReplace(std::string& s, const std::string& from, const std::string& to);
  static void        _strTrim(std::string& s);
  static std::string _urlDecode(const char* src, size_t len);
  static std::string _formParam(const char* body, const char* name);
  static bool        _readBody(httpd_req_t* req, std::string& out);

  // ---------------------------------------------------------------------------
  // Static trampoline handlers (httpd requires plain function pointers)
  // ---------------------------------------------------------------------------
  static esp_err_t _s_root(httpd_req_t* req);
  static esp_err_t _s_save(httpd_req_t* req);
  static esp_err_t _s_clearbonds(httpd_req_t* req);
  static esp_err_t _s_update(httpd_req_t* req);

  // ---------------------------------------------------------------------------
  // Web handler implementations
  // ---------------------------------------------------------------------------
  void _handleRoot(httpd_req_t* req);
  void _handleSave(httpd_req_t* req);
  void _handleClearBonds(httpd_req_t* req);
  void _handleUpdate(httpd_req_t* req);
};
